version: "3"

services:
  backapp:
    container_name: backapp
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    image: site
    restart: unless-stopped
    volumes:
      - ./site:/var/www
    networks:
      - scorpionet

  backserver:
    container_name: backserver
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./site:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - backapp
      - backdb
    networks:
      - scorpionet

  backdb:
    container_name: backdb
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - ./env/db.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - scorpionet

  backphpmyadmin:
    container_name: backphpmydmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - scorpionet

volumes:
  dbdata:
    driver: local

networks:
  scorpionet:


