version: "3"

services:
  back-app:
    container_name: back-app
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    image: site
    restart: unless-stopped
    volumes:
      - ./site:/var/www
    networks:
      - scorpionet

  back-server:
    container_name: back-server
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - back-app
      - back-db
    networks:
      - scorpionet

  back-db:
    container_name: back-db
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - ./env/db.env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - scorpionet

  back-phpmyadmin:
    container_name: back-phpmydmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - "8081:80"
    networks:
      - scorpionet

volumes:
  dbdata:
    driver: local

networks:
  scorpionet:
    name: scorpionet
    driver: bridge

